name: MakeCode Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: npm install -g pxt
      - name: Build MakeCode Arcade project
        run: pxt arcade build
      - name: Deploy Arcade pages
        run: pxt staticpkg
